server:
  port: 8001
spring:
  jpa:
    show-sql: true
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-provider-user
    #main:
    #allow-bean-definition-overriding: true
logging:
  level:
    root: info
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://user:xiaoqi123@localhost:8761/eureka/                #http://peer2:8762/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

